# Generated by Django 2.2.7 on 2019-11-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_name', models.CharField(max_length=40)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=6)),
                ('stock', models.CharField(max_length=2)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Black', 'Black'), ('Green', 'Green'), ('Blue', 'Blue')], max_length=5)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=6)),
                ('quantity', models.CharField(max_length=2)),
            ],
        ),
    ]
